### ISSUE TITLE
bot 使用流程實作

### ISSUE THREAD

**Issue by homerchen19** [PPAV-inc/telegram-bot#6]
- [x] 選擇語言 (#5)
- [x] 顯示正確語言的免責聲明、是否接受的按鈕 (#5)
- [x] 每次 query 前確認使用者是否已接受免責聲明 (#7)
- [x] persistent menu 實作 (#7)
  - [x] 免責聲明 (#7)
  - [x] 關於 PPAV (#7)
  - [x] 意見回饋 (#7)
  - [x] 聯絡我們 (#7)
  - [x] 設定 (#7)
- [x] query 後的影片按鈕設計 (#21)
  - [x] 頁數控制、第一頁、最後一頁 (#21)
  - [x] 前往影片網頁 (#21)
- [x] 閱後即焚 (#7)
  - [x] 讓使用者選擇啟動或關閉 (#14)
  - [x] 15 秒後自動刪掉結果 (#14)

**Comment by homerchen19** [comment]
搜尋後影片的
callback_data: `messageId="${messageId}"&query="${query}"&page="${page}"`
